packages:
  - packages/*

allowBuilds:
  bcrypt: true
  better-sqlite3: true
  core-js: true
  esbuild: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
  yencode: true

patchedDependencies:
  '@viren070/parse-torrent-title@0.8.6': 'patches/@viren070__parse-torrent-title@0.8.6.patch'
  stremthru: patches/stremthru.patch
  yencode@1.2.4: patches/yencode@1.2.4.patch
